server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: <your username>
    password: <your password>
  # thymeleaf
  thymeleaf:
    cache: true

  # email
  mail:
    host: smtp.163.com # smtp.qq.com
    username: <your email>
    password: <your password>
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # redis
  redis:
    database: 11
    host: localhost
    port: 6379

mybatis:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    # 自动生成 id
    use-generated-keys: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.community.entity

# community
community:
  path:
    domain: http://ip:port


# aliyun OSS
aliyun:
  oss:
    file:
      endpoint: <your endpoint>
      keyid: <your keyid>
      keysecret: <your keysecret>
      # bucket可以在控制台创建
      bucketname: <your bucketname>

