server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: toor
  thymeleaf:
    cache: false
  # 邮件激活配置
  mail:
    host: smtp.qq.com
    port: 465
    username: weizujie@vip.qq.com
    # 授权码，并非登录密码
    password: nuzudxbzwjmjbahf
    default-encoding: UTF-8
    # 开启 ssl，不然会报 503 错误
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # redis
  redis:
    database: 11
    host: localhost
    port: 6379

mybatis:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    # 自动生成 id
    use-generated-keys: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.community.entity

# community
community:
  path:
    domain: http://localhost:8080
    upload: E:/Code/Java/SpringBoot/community/upload

# aliyun OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI4GAK8Ei4gy9MTqMHohyP
      keysecret: 4t859qr4Vy6HmkXDvjbGLUy7SiVbmc
      # bucket可以在控制台创建，也可以使用 java 代码创建
      bucketname: weizujie

